<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Webkul\Security\Models\User;

class HardwareProductSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();
        $now = Carbon::now();

        $companyId = DB::table('companies')->value('id');
        $uomUnitId = 1;
        $uomKgId = 3;
        $uomMId = 10;
        $uomMmId = 11;
        $uomCmId = 13;
        $uomM2Id = 18;
        $uomLId = 20;
        $uomGId = 4;

        $subCategories = [
            [
                'id'          => 20,
                'parent_id'   => 6,
                'name'        => 'Herramientas Eléctricas',
                'full_name'   => 'All / Saleable / Herramientas Eléctricas',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 21,
                'parent_id'   => 6,
                'name'        => 'Herramientas Manuales',
                'full_name'   => 'All / Saleable / Herramientas Manuales',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 22,
                'parent_id'   => 6,
                'name'        => 'Materiales de Construcción',
                'full_name'   => 'All / Saleable / Materiales de Construcción',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 23,
                'parent_id'   => 6,
                'name'        => 'Fontanería',
                'full_name'   => 'All / Saleable / Fontanería',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 24,
                'parent_id'   => 6,
                'name'        => 'Electricidad',
                'full_name'   => 'All / Saleable / Electricidad',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 25,
                'parent_id'   => 6,
                'name'        => 'Pintura',
                'full_name'   => 'All / Saleable / Pintura',
                'parent_path' => '/1/6/',
            ],
            [
                'id'          => 26,
                'parent_id'   => 6,
                'name'        => 'Jardinería',
                'full_name'   => 'All / Saleable / Jardinería',
                'parent_path' => '/1/6/',
            ],
        ];

        foreach ($subCategories as $cat) {
            $cat['creator_id'] = $user?->id;
            $cat['created_at'] = $now;
            $cat['updated_at'] = $now;
            DB::table('products_categories')->updateOrInsert(
                ['id' => $cat['id']],
                $cat
            );
        }

        $products = [
            // ─── Herramientas Eléctricas (category_id: 20) ───
            [
                'name'             => 'Taladro Percutor 800W ½"',
                'reference'        => 'HE-001',
                'barcode'          => '7801234560011',
                'price'            => 32990,
                'cost'             => 19800,
                'weight'           => 2.5,
                'volume'           => 0.008,
                'description'      => 'Taladro percutor con mandril ½", 800W de potencia, velocidad variable 0-2800 RPM, incluye maletín y accesorios.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Taladro Inalámbrico 18V 2 Baterías',
                'reference'        => 'HE-002',
                'barcode'          => '7801234560028',
                'price'            => 45990,
                'cost'             => 27500,
                'weight'           => 1.8,
                'volume'           => 0.006,
                'description'      => 'Taladro inalámbrico 18V, incluye 2 baterías de litio 2Ah, cargador, velocidad variable 0-1500 RPM, maletín.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Amoladora Angular 4½" 850W',
                'reference'        => 'HE-003',
                'barcode'          => '7801234560035',
                'price'            => 28990,
                'cost'             => 17400,
                'weight'           => 2.1,
                'volume'           => 0.007,
                'description'      => 'Amoladora angular 4½", 850W, 11000 RPM, disco incluido, interruptor de seguridad, carcasa reforzada.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Sierra Circular 7¼" 1400W',
                'reference'        => 'HE-004',
                'barcode'          => '7801234560042',
                'price'            => 39990,
                'cost'             => 24000,
                'weight'           => 4.2,
                'volume'           => 0.015,
                'description'      => 'Sierra circular 7¼", 1400W, 5000 RPM, corte máximo 65mm a 90°, guía láser incluida, maletín.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Lijadora Orbital 300W ⅓ Hoja',
                'reference'        => 'HE-005',
                'barcode'          => '7801234560059',
                'price'            => 22990,
                'cost'             => 13800,
                'weight'           => 1.5,
                'volume'           => 0.005,
                'description'      => 'Lijadora orbital ⅓ de hoja, 300W, 12000 OPM, sistema de extracción de polvo, incluye 5 lijas.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Atornillador Eléctrico 12V Recargable',
                'reference'        => 'HE-006',
                'barcode'          => '7801234560066',
                'price'            => 26990,
                'cost'             => 16200,
                'weight'           => 1.2,
                'volume'           => 0.004,
                'description'      => 'Atornillador eléctrico 12V, batería de litio integrada, cargador USB, 30 puntas, 200 RPM.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Pistola de Calor 2000W',
                'reference'        => 'HE-007',
                'barcode'          => '7801234560073',
                'price'            => 15990,
                'cost'             => 9600,
                'weight'           => 0.8,
                'volume'           => 0.003,
                'description'      => 'Pistola de calor 2000W, temperatura regulable 60-600°C, 2 boquillas, flujo de aire 250-500 L/min.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Hidrolavadora 1600W 110 Bar',
                'reference'        => 'HE-008',
                'barcode'          => '7801234560080',
                'price'            => 62990,
                'cost'             => 37800,
                'weight'           => 6.5,
                'volume'           => 0.025,
                'description'      => 'Hidrolavadora eléctrica 1600W, presión máxima 110 bar, caudal 400 L/h, manguera 8m, boquilla regulable.',
                'category_id'      => 20,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Herramientas Manuales (category_id: 21) ───
            [
                'name'             => 'Martillo de Carpintero 500g',
                'reference'        => 'HM-001',
                'barcode'          => '7801234560103',
                'price'            => 4990,
                'cost'             => 2500,
                'weight'           => 0.5,
                'volume'           => 0.001,
                'description'      => 'Martillo de carpintero 500g, mango de madera reforzada, cabeza de acero forjado templado.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Juego de Destornilladores 6 Piezas',
                'reference'        => 'HM-002',
                'barcode'          => '7801234560110',
                'price'            => 6990,
                'cost'             => 3500,
                'weight'           => 0.6,
                'volume'           => 0.002,
                'description'      => 'Juego 6 destornilladores: 3 planos y 3 phillips, mangos ergonómicos antideslizantes, puntas magnéticas.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Llave Ajustable 12"',
                'reference'        => 'HM-003',
                'barcode'          => '7801234560127',
                'price'            => 8990,
                'cost'             => 4500,
                'weight'           => 0.7,
                'volume'           => 0.002,
                'description'      => 'Llave ajustable 12", acero al carbono forjado, cromo pulido, escala graduada, apertura máxima 35mm.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Alicate Universal 8"',
                'reference'        => 'HM-004',
                'barcode'          => '7801234560134',
                'price'            => 5990,
                'cost'             => 3000,
                'weight'           => 0.3,
                'volume'           => 0.001,
                'description'      => 'Alicate universal 8", acero al cromo vanadio, mangos aislados, corte lateral y mordaza dentada.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Cinta Métrica 5m x 19mm',
                'reference'        => 'HM-005',
                'barcode'          => '7801234560141',
                'price'            => 3990,
                'cost'             => 1800,
                'weight'           => 0.2,
                'volume'           => 0.001,
                'description'      => 'Cinta métrica 5m, ancho 19mm, cinta de acero templado con recubrimiento nylon, gancho magnético.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Nivel de Burbuja 60cm Aluminio',
                'reference'        => 'HM-006',
                'barcode'          => '7801234560158',
                'price'            => 5490,
                'cost'             => 2700,
                'weight'           => 0.4,
                'volume'           => 0.003,
                'description'      => 'Nivel de burbuja 60cm, perfil de aluminio, 3 viales (horizontal, vertical, 45°), tapas de impacto.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Serrucho 20" Mango Ergonómico',
                'reference'        => 'HM-007',
                'barcode'          => '7801234560165',
                'price'            => 6490,
                'cost'             => 3200,
                'weight'           => 0.5,
                'volume'           => 0.002,
                'description'      => 'Serrucho 20", hoja de acero al carbono templado, mango ergonómico de goma, triple filo triscado.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Set Llaves Allen 9 Piezas',
                'reference'        => 'HM-008',
                'barcode'          => '7801234560172',
                'price'            => 4490,
                'cost'             => 2200,
                'weight'           => 0.25,
                'volume'           => 0.001,
                'description'      => 'Set 9 llaves Allen 1.5-10mm, acero al cromo vanadio, estuche organizador plegable.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Cortadora de Cerámica Manual 400mm',
                'reference'        => 'HM-009',
                'barcode'          => '7801234560189',
                'price'            => 18990,
                'cost'             => 11400,
                'weight'           => 3.2,
                'volume'           => 0.012,
                'description'      => 'Cortadora de cerámica manual 400mm, corte recto y diagonal, guía metálica graduada, rueda de carburo de tungsteno.',
                'category_id'      => 21,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Materiales de Construcción (category_id: 22) ───
            [
                'name'             => 'Cemento Portland Grado 42.5 42.5kg',
                'reference'        => 'MC-001',
                'barcode'          => '7801234560202',
                'price'            => 7990,
                'cost'             => 5600,
                'weight'           => 42.5,
                'volume'           => 0.032,
                'description'      => 'Cemento Portland grado 42.5, saco 42.5kg, uso general en construcción, fraguado normal.',
                'category_id'      => 22,
                'uom_id'           => $uomKgId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Cal de Construcción 25kg',
                'reference'        => 'MC-002',
                'barcode'          => '7801234560219',
                'price'            => 4990,
                'cost'             => 3000,
                'weight'           => 25,
                'volume'           => 0.025,
                'description'      => 'Cal de construcción hidratada, saco 25kg, para morteros y estucos.',
                'category_id'      => 22,
                'uom_id'           => $uomKgId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Yeso de Construcción 25kg',
                'reference'        => 'MC-003',
                'barcode'          => '7801234560226',
                'price'            => 5490,
                'cost'             => 3300,
                'weight'           => 25,
                'volume'           => 0.028,
                'description'      => 'Yeso de construcción, saco 25kg, fraguado rápido, para estucos y molduras.',
                'category_id'      => 22,
                'uom_id'           => $uomKgId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Ladrillo Fiscal 10x20x40cm',
                'reference'        => 'MC-004',
                'barcode'          => '7801234560233',
                'price'            => 890,
                'cost'             => 530,
                'weight'           => 8.5,
                'volume'           => 0.008,
                'description'      => 'Ladrillo fiscal 10x20x40cm, cerámica roja, para muros y tabiques.',
                'category_id'      => 22,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Pegamento Cerámico 25kg',
                'reference'        => 'MC-005',
                'barcode'          => '7801234560240',
                'price'            => 8990,
                'cost'             => 5400,
                'weight'           => 25,
                'volume'           => 0.022,
                'description'      => 'Pegamento cerámico 25kg, adhesivo para cerámica y porcelanato, uso interior y exterior.',
                'category_id'      => 22,
                'uom_id'           => $uomKgId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Plancha Yeso-Cartón 1.2x2.4m 12.5mm',
                'reference'        => 'MC-006',
                'barcode'          => '7801234560257',
                'price'            => 9990,
                'cost'             => 6000,
                'weight'           => 25.5,
                'volume'           => 0.036,
                'description'      => 'Plancha yeso-cartón 1.2x2.4m, espesor 12.5mm, para tabiques y cielos, bordes rebajados.',
                'category_id'      => 22,
                'uom_id'           => $uomM2Id,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Plancha Fibrocemento 3x1.2m 6mm',
                'reference'        => 'MC-007',
                'barcode'          => '7801234560264',
                'price'            => 15990,
                'cost'             => 9600,
                'weight'           => 38,
                'volume'           => 0.022,
                'description'      => 'Plancha fibrocemento 3x1.2m, espesor 6mm, para revestimiento y cubiertas, resistente a la humedad.',
                'category_id'      => 22,
                'uom_id'           => $uomM2Id,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Fierro Estriado 12mm x 6m',
                'reference'        => 'MC-008',
                'barcode'          => '7801234560271',
                'price'            => 12990,
                'cost'             => 7800,
                'weight'           => 10.7,
                'volume'           => 0.002,
                'description'      => 'Fierro estriado diámetro 12mm, longitud 6m, grado A44-28H, para estructuras de hormigón armado.',
                'category_id'      => 22,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Fontanería (category_id: 23) ───
            [
                'name'             => 'Tubería PVC 110mm x 3m',
                'reference'        => 'FO-001',
                'barcode'          => '7801234560301',
                'price'            => 6990,
                'cost'             => 4200,
                'weight'           => 2.8,
                'volume'           => 0.018,
                'description'      => 'Tubería PVC 110mm diámetro, longitud 3m, para alcantarillado y aguas lluvias, paredestructurada.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Codo PVC 110mm 45°',
                'reference'        => 'FO-002',
                'barcode'          => '7801234560318',
                'price'            => 1290,
                'cost'             => 650,
                'weight'           => 0.15,
                'volume'           => 0.001,
                'description'      => 'Codo PVC 110mm 45°, para sistema de alcantarillado, unión campana.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Válvula de Paso ¾" Latón',
                'reference'        => 'FO-003',
                'barcode'          => '7801234560325',
                'price'            => 5490,
                'cost'             => 3300,
                'weight'           => 0.35,
                'volume'           => 0.001,
                'description'      => 'Válvula de paso ¾", cuerpo de latón cromado, rosca NPT, para agua potable.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Grifo Cocina Monomando Cromo',
                'reference'        => 'FO-004',
                'barcode'          => '7801234560332',
                'price'            => 22990,
                'cost'             => 13800,
                'weight'           => 1.5,
                'volume'           => 0.004,
                'description'      => 'Grifo cocina monomando cromado, caño giratorio 360°, aireador, mangueras flexibles 50cm.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Sifón Lavatorio 1¼" Cromado',
                'reference'        => 'FO-005',
                'barcode'          => '7801234560349',
                'price'            => 4990,
                'cost'             => 2500,
                'weight'           => 0.2,
                'volume'           => 0.001,
                'description'      => 'Sifón para lavatorio 1¼", cuerpo PVC cromado, trampa de agua, desmontable para limpieza.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Cinta Teflón 12mm x 15m',
                'reference'        => 'FO-006',
                'barcode'          => '7801234560356',
                'price'            => 990,
                'cost'             => 500,
                'weight'           => 0.05,
                'volume'           => 0.0001,
                'description'      => 'Cinta teflón para sellado de roscas 12mm ancho, 15m largo, sella uniones hidráulicas.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Tubería PPR 25mm x 4m Agua Caliente',
                'reference'        => 'FO-007',
                'barcode'          => '7801234560363',
                'price'            => 8490,
                'cost'             => 5100,
                'weight'           => 1.2,
                'volume'           => 0.006,
                'description'      => 'Tubería PPR 25mm diámetro, 4m longitud, termofusión, para agua potable caliente y fría.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Llave Paso Jardín ¾" Bronce',
                'reference'        => 'FO-008',
                'barcode'          => '7801234560370',
                'price'            => 3990,
                'cost'             => 2000,
                'weight'           => 0.25,
                'volume'           => 0.001,
                'description'      => 'Llave de paso para jardín ¾", cuerpo bronce, salida para manguera, rosca NPT.',
                'category_id'      => 23,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Electricidad (category_id: 24) ───
            [
                'name'             => 'Cable THHN 2.5mm² x 100m',
                'reference'        => 'EL-001',
                'barcode'          => '7801234560400',
                'price'            => 22990,
                'cost'             => 13800,
                'weight'           => 3.5,
                'volume'           => 0.005,
                'description'      => 'Cable THHN 2.5mm², 100m, cobre electrolítico, aislamiento PVC, 600V, para instalaciones eléctricas.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Interruptor Simple Blanco',
                'reference'        => 'EL-002',
                'barcode'          => '7801234560417',
                'price'            => 2990,
                'cost'             => 1500,
                'weight'           => 0.08,
                'volume'           => 0.0003,
                'description'      => 'Interruptor simple blanco, 10A 250V, mecanismo universal, placa decorativa.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Enchufe Universal Blanco Con Tapa',
                'reference'        => 'EL-003',
                'barcode'          => '7801234560424',
                'price'            => 2490,
                'cost'             => 1200,
                'weight'           => 0.08,
                'volume'           => 0.0003,
                'description'      => 'Enchufe universal 10A 250V, blanco, con tapa protectora, mecanismo con placa.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Portalámpara Estándar E27',
                'reference'        => 'EL-004',
                'barcode'          => '7801234560431',
                'price'            => 1490,
                'cost'             => 700,
                'weight'           => 0.05,
                'volume'           => 0.0002,
                'description'      => 'Portalámpara estándar E27, porcelana blanca, 660W 250V, para interiores.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Tubo Conduit 20mm x 3m',
                'reference'        => 'EL-005',
                'barcode'          => '7801234560448',
                'price'            => 3490,
                'cost'             => 2100,
                'weight'           => 0.8,
                'volume'           => 0.004,
                'description'      => 'Tubo conduit PVC 20mm diámetro, 3m, para canalización eléctrica, incluye unión.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Tablero Eléctrico 8 Espacios',
                'reference'        => 'EL-006',
                'barcode'          => '7801234560455',
                'price'            => 15990,
                'cost'             => 9600,
                'weight'           => 1.8,
                'volume'           => 0.007,
                'description'      => 'Tablero eléctrico 8 espacios, gabinete metálico, puerta con cerradura, barra de tierra incluida.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Termomagnético 20A 1Polo',
                'reference'        => 'EL-007',
                'barcode'          => '7801234560462',
                'price'            => 4990,
                'cost'             => 2500,
                'weight'           => 0.12,
                'volume'           => 0.0004,
                'description'      => 'Disyuntor termomagnético 20A 1 polo, 6kA, 240/415V, curva C, riel DIN.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Cable USB-C Carga Rápida 2m',
                'reference'        => 'EL-008',
                'barcode'          => '7801234560479',
                'price'            => 3990,
                'cost'             => 2000,
                'weight'           => 0.06,
                'volume'           => 0.0001,
                'description'      => 'Cable USB-C carga rápida 2m, trenzado nylon, 60W Power Delivery, compatible universal.',
                'category_id'      => 24,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Pintura (category_id: 25) ───
            [
                'name'             => 'Látex Interior 20L Blanco Premium',
                'reference'        => 'PI-001',
                'barcode'          => '7801234560509',
                'price'            => 28990,
                'cost'             => 17400,
                'weight'           => 24,
                'volume'           => 0.02,
                'description'      => 'Látex interior 20L blanco premium, lavable, cubriente y antimoho, secado rápido.',
                'category_id'      => 25,
                'uom_id'           => $uomLId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Esmalte Sintético 1L Blanco',
                'reference'        => 'PI-002',
                'barcode'          => '7801234560516',
                'price'            => 8990,
                'cost'             => 5400,
                'weight'           => 1.2,
                'volume'           => 0.001,
                'description'      => 'Esmalte sintético 1L blanco, brillante, para maderas y metales, secado al horno.',
                'category_id'      => 25,
                'uom_id'           => $uomLId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Sellador Acrílico 20L',
                'reference'        => 'PI-003',
                'barcode'          => '7801234560523',
                'price'            => 18990,
                'cost'             => 11400,
                'weight'           => 22,
                'volume'           => 0.02,
                'description'      => 'Sellador acrílico 20L, para muros interiores y exteriores, fija el polvo, prepara la superficie.',
                'category_id'      => 25,
                'uom_id'           => $uomLId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Brocha 2" Profesional',
                'reference'        => 'PI-004',
                'barcode'          => '7801234560530',
                'price'            => 2490,
                'cost'             => 1200,
                'weight'           => 0.08,
                'volume'           => 0.0003,
                'description'      => 'Brocha profesional 2", cerda sintética, mango de madera barnizada, virola de acero inoxidable.',
                'category_id'      => 25,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Rodillo Lana 9" + Kit',
                'reference'        => 'PI-005',
                'barcode'          => '7801234560547',
                'price'            => 3490,
                'cost'             => 1700,
                'weight'           => 0.2,
                'volume'           => 0.001,
                'description'      => 'Rodillo lana 9", incluye mango y bandeja, para pintura látex y esmalte.',
                'category_id'      => 25,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Diluyente Aguarrás 1L',
                'reference'        => 'PI-006',
                'barcode'          => '7801234560554',
                'price'            => 3490,
                'cost'             => 1700,
                'weight'           => 0.9,
                'volume'           => 0.001,
                'description'      => 'Aguarrás mineral 1L, diluyente para esmaltes sintéticos y barnices, limpia brochas y rodillos.',
                'category_id'      => 25,
                'uom_id'           => $uomLId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Pintura en Spray 400ml Negro',
                'reference'        => 'PI-007',
                'barcode'          => '7801234560561',
                'price'            => 3990,
                'cost'             => 2000,
                'weight'           => 0.35,
                'volume'           => 0.0004,
                'description'      => 'Pintura spray 400ml, color negro mate, secado rápido, para metales y superficies.',
                'category_id'      => 25,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Masilla Plástica 500g',
                'reference'        => 'PI-008',
                'barcode'          => '7801234560578',
                'price'            => 2990,
                'cost'             => 1500,
                'weight'           => 0.5,
                'volume'           => 0.0004,
                'description'      => 'Masilla plástica 500g, para reparación de maderas y muros, secado rápido, lijable.',
                'category_id'      => 25,
                'uom_id'           => $uomGId,
                'uom_po_id'        => $uomUnitId,
            ],

            // ─── Jardinería (category_id: 26) ───
            [
                'name'             => 'Manguera Jardín ½" x 15m',
                'reference'        => 'JA-001',
                'barcode'          => '7801234560608',
                'price'            => 9990,
                'cost'             => 6000,
                'weight'           => 1.5,
                'volume'           => 0.004,
                'description'      => 'Manguera jardín ½" diámetro, 15m, PVC reforzado con tripa textil, conexiones plásticas.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Regadera Jardín 10L Plástica',
                'reference'        => 'JA-002',
                'barcode'          => '7801234560615',
                'price'            => 5990,
                'cost'             => 3000,
                'weight'           => 0.4,
                'volume'           => 0.01,
                'description'      => 'Regadera jardín 10L, plástico resistente UV, rosetón removible, asa ergonómica.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Tijera de Podar Acero',
                'reference'        => 'JA-003',
                'barcode'          => '7801234560622',
                'price'            => 8990,
                'cost'             => 4500,
                'weight'           => 0.3,
                'volume'           => 0.001,
                'description'      => 'Tijera de podar acero al carbono, hojas templadas, mango ergonómico antideslizante, resorte de apertura.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Rastrillo Acero 10 Dientes',
                'reference'        => 'JA-004',
                'barcode'          => '7801234560639',
                'price'            => 4490,
                'cost'             => 2200,
                'weight'           => 0.6,
                'volume'           => 0.003,
                'description'      => 'Rastrillo acero 10 dientes, mango madera 120cm, para jardinería y limpieza de exteriores.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Pala Jardín Punta Redonda',
                'reference'        => 'JA-005',
                'barcode'          => '7801234560646',
                'price'            => 5990,
                'cost'             => 3000,
                'weight'           => 1.0,
                'volume'           => 0.003,
                'description'      => 'Pala jardín punta redonda, hoja acero templado, mango madera 110cm, con travesaño.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
            [
                'name'             => 'Carretilla 60L Acero',
                'reference'        => 'JA-006',
                'barcode'          => '7801234560653',
                'price'            => 28990,
                'cost'             => 17400,
                'weight'           => 12,
                'volume'           => 0.06,
                'description'      => 'Carretilla 60L, tolva acero laminado, manigua reforzada, neumático inflable 4.10-6.',
                'category_id'      => 26,
                'uom_id'           => $uomUnitId,
                'uom_po_id'        => $uomUnitId,
            ],
        ];

        $insertData = [];
        foreach ($products as $product) {
            $insertData[] = [
                'type'                 => 'goods',
                'name'                 => $product['name'],
                'service_tracking'     => 'none',
                'reference'            => $product['reference'],
                'barcode'              => $product['barcode'],
                'price'                => $product['price'],
                'cost'                 => $product['cost'],
                'volume'               => $product['volume'] ?? null,
                'weight'               => $product['weight'] ?? null,
                'description'          => $product['description'],
                'description_purchase' => $product['description'],
                'description_sale'     => $product['description'],
                'enable_sales'         => true,
                'enable_purchase'      => true,
                'is_favorite'          => false,
                'is_storable'          => true,
                'is_configurable'      => null,
                'sort'                 => null,
                'images'               => null,
                'parent_id'            => null,
                'uom_id'               => $product['uom_id'],
                'uom_po_id'            => $product['uom_po_id'],
                'category_id'          => $product['category_id'],
                'company_id'           => $companyId,
                'creator_id'           => $user?->id,
                'created_at'           => $now,
                'updated_at'           => $now,
            ];
        }

        DB::table('products_products')->insert($insertData);

        $this->command?->info(sprintf('✅ %d productos de ferretería mayorista creados con precios en CLP.', count($products)));
    }
}
